# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
        - replace_match(attributes["service.name"], "unknown_service", "cpp_service")
exporters:
  otlp:
    endpoint: 10.241.0.5:24317
    tls:
      insecure: true
  file:
    path: ./metrics.json
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters: [otlp]
    metrics:
      receivers: [hostmetrics, otlp]
      exporters: [otlp,file]
    logs:
      receivers: [otlp]
      exporters: [otlp]
