# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:
    root_path: /hostfs
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
        - replace_match(attributes["service.name"], "unknown_service", "cpp_service")
exporters:
  otlp:
    endpoint: vsi-s390x-01:24317
    tls:
      insecure: true
  file:
    path: /tmp/metrics.json
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters: [otlp]
    metrics:
      receivers: [hostmetrics, otlp]
      exporters: [otlp,file]
    logs:
      receivers: [otlp]
      exporters: [otlp]
