# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

# Gateway configuration for demonstratrating the collector on linux/s390x.

receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: "localhost:4317"
      http: 
        endpoint: "localhost:4318"
processors:
  batch:
exporters:
  otlp:
    endpoint: backend-s390x-01:24317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: http://backend-s390x-01:3100/loki/api/v1/push
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
