# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

# Gateway configuration for demonstratrating the collector on linux/s390x.

receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  otlp/1:
    endpoint: vsi-s390x-01:24317
    tls:
      insecure: true
  otlp/2:
    endpoint: otlp-green-saas.instana.io:4317
    headers:
      x-instana-key: xxxxxxx
      x-instana-host: vsi-s390x-01
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: http://vsi-s390x-01:3100/loki/api/v1/push
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]      
      exporters: [otlp/1,otlp/2]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,otlp/2]
    logs:
      receivers: [otlp]
      processors: [batch]      
      exporters: [loki,otlp/2]
