version: "3.7"
services:
  jaeger-service:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 24317:4317
      - 16686:16686
    networks:
      - nw-lab001
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  prometheus-service:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml/:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    ports:
      - 9090:9090
    networks:
      - nw-lab001
  grafana-service:
    image: ubuntu/grafana:8.2-22.04_beta
    container_name: grafana
    depends_on:
      - jaeger-service
      - prometheus-service
      - loki-service
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/etc/grafana/dashboards
    networks:
      - nw-lab001
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  loki-service:
    image: ubuntu/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml    
    command: 
      -config.file=/etc/loki/config.yaml
    networks:
      - nw-lab001
  collector-gateway-service:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector-gateway
    depends_on:
      - jaeger-service
      - prometheus-service
      - loki-service
    ports: 
      - 14317:4317
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter
    volumes:
      - ./config/collector/gateway.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - nw-lab001
  collector-agent-service:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector-agent
    depends_on:
      - collector-gateway-service
    ports: 
      - 4317:4317
      - 4318:4318
    volumes:
      - ./config/collector/agent.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - nw-lab001
networks:
  nw-lab001:

